# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(1369, 791)

        self.gridLayout = QtWidgets.QGridLayout(Window)
        self.gridLayout.setObjectName("gridLayout")

        self.splitter = QtWidgets.QSplitter(Window)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")

        # Left box label
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)

        # Left box window
        self.src_file_list = QtWidgets.QListWidget(self.widget)
        self.src_file_list.setObjectName("src_file_list")
        self.verticalLayout.addWidget(self.src_file_list)

        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        # Right box label
        self.label_3 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)

        # Right box window
        self.dest_file_list = QtWidgets.QListWidget(self.widget1)
        self.dest_file_list.setObjectName("dest_file_list")
        self.verticalLayout_3.addWidget(self.dest_file_list)

        self.gridLayout.addWidget(self.splitter, 2, 0, 1, 3)

        # Source directory text bar at top
        self.dir_edit = QtWidgets.QLineEdit(Window)
        self.dir_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.dir_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.dir_edit.setReadOnly(True)
        self.dir_edit.setObjectName("dir_edit")
        self.gridLayout.addWidget(self.dir_edit, 1, 0, 1, 2)

        # Source directory label
        self.label = QtWidgets.QLabel(Window)
        self.label.setMinimumSize(QtCore.QSize(0, 15))
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 3)

        # Filename prefix label
        self.label_4 = QtWidgets.QLabel(Window)
        self.label_4.setMinimumSize(QtCore.QSize(0, 15))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 3)

        # Load Files button
        self.load_files_button = QtWidgets.QPushButton(Window)
        self.load_files_button.setMinimumSize(QtCore.QSize(0, 30))
        self.load_files_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.load_files_button.setObjectName("load_files_button")
        self.gridLayout.addWidget(self.load_files_button, 1, 2, 1, 1)

        # Prefix text bar at bottom
        self.prefix_edit = QtWidgets.QLineEdit(Window)
        self.prefix_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.prefix_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.prefix_edit.setReadOnly(True)
        self.prefix_edit.setObjectName("prefix_edit")
        self.gridLayout.addWidget(self.prefix_edit, 4, 0, 1, 1)

        # Progress bar
        self.progress_bar = QtWidgets.QProgressBar(Window)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progress_bar.sizePolicy().hasHeightForWidth())
        self.progress_bar.setSizePolicy(sizePolicy)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setAlignment(QtCore.Qt.AlignCenter)
        self.progress_bar.setTextVisible(True)
        self.progress_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 5, 0, 1, 3)

        # Filename extension chooser
        self.Extension_Choice_Box = QtWidgets.QComboBox(Window)
        self.Extension_Choice_Box.setMinimumSize(QtCore.QSize(0, 30))
        self.Extension_Choice_Box.setMaximumSize(QtCore.QSize(16777215, 30))
        self.Extension_Choice_Box.setObjectName("Extension_Choice_Box")
        self.Extension_Choice_Box.addItem("")
        self.Extension_Choice_Box.addItem("")
        self.Extension_Choice_Box.addItem("")
        self.Extension_Choice_Box.addItem("")
        self.Extension_Choice_Box.addItem("")
        self.gridLayout.addWidget(self.Extension_Choice_Box, 4, 1, 1, 1)

        # Rename files button
        self.rename_files_button = QtWidgets.QPushButton(Window)
        self.rename_files_button.setMinimumSize(QtCore.QSize(0, 30))
        self.rename_files_button.setMaximumSize(QtCore.QSize(16777215, 30))
        self.rename_files_button.setObjectName("rename_files_button")
        self.gridLayout.addWidget(self.rename_files_button, 4, 2, 1, 1)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "File Renamer"))
        self.label_2.setText(_translate("Window", "Files to Rename"))
        self.label_3.setText(_translate("Window", "Renamed Files"))
        self.label.setText(_translate("Window", "Source Directory:"))
        self.label_4.setText(_translate("Window", "Filename Prefix:"))
        self.load_files_button.setText(_translate("Window", "&Load Files"))
        self.prefix_edit.setPlaceholderText(
            _translate("Window", "Rename your files to...")
        )
        self.Extension_Choice_Box.setItemText(0, _translate("Window", "*.jpg"))
        self.Extension_Choice_Box.setItemText(1, _translate("Window", "*.json"))
        self.Extension_Choice_Box.setItemText(2, _translate("Window", "*.pdf"))
        self.Extension_Choice_Box.setItemText(3, _translate("Window", "*.png"))
        self.Extension_Choice_Box.setItemText(4, _translate("Window", "*.txt"))
        self.rename_files_button.setText(_translate("Window", "&Rename"))
        self.rename_files_button.setShortcut(_translate("Window", "R"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Window = QtWidgets.QWidget()
    ui = Ui_Window()
    ui.setupUi(Window)
    Window.show()
    sys.exit(app.exec_())
